### ISSUE TITLE
Beta 1 Launch Checklist

### ISSUE THREAD

**Issue by viniciusaportela** [viniciusaportela/sharetic#1]
## Beta 1 Release

- [ ] Google Refresh Token
- [ ] Register with Google Authentication
- [ ] Show alert to new users to redirect to main page
- [ ] Show my Divulgations
	- [ ] Instagram Profile
	- [ ] Instagram Comments
	- [ ] Instagram Likes
	- [ ] Follow Facebook Page
	- [ ] Facebook Like
	- [ ] Facebook Comment
- [ ] Implemment Facebook
	- [ ] Facebook Profile
	- [ ] Facebook Like
	- [ ] Facebook Comment
- [ ] Choose between Facebook and Instagram on Register
- [ ] Doesn't allow API requests if user doesnt have verified email
- [ ] Make PendentsCards responsive
- [ ] Remove Edit Button from Profile
- [ ] On finish Confirm/Reject response, close request locally
- [ ] Send confirmation email again
- [ ] Remove console.log()
